# Generated by Django 4.2.3 on 2023-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autora', models.CharField(max_length=256)),
                ('nombre_libro', models.CharField(max_length=256)),
                ('fecha_publicacion', models.DateField(null=True)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nuevas_Autoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=64)),
                ('autora', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Top10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autora', models.CharField(max_length=256)),
                ('nombre_libro', models.CharField(max_length=256)),
                ('genero', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
