# Generated by Django 4.2.3 on 2023-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='comentario',
            field=models.CharField(default='Reseña', max_length=600),
            preserve_default=False,
        ),
    ]
